### ISSUE TITLE
Uncaught TypeError: t.editor.setMarkdown is not a function

### ISSUE THREAD

**Issue by hiwepy** [Aubrey-J/vue-editormd-wrap#1]
1、按使用说明进行操作，浏览器报错：样式表单 http://localhost:8080/editor-md/css/editormd.min.css 未载入，因为它的 MIME 类型 "text/html" 不是 "text/css"。
![图片](https://user-images.githubusercontent.com/20489781/181013578-f0dcd21f-b719-4edd-baed-8c9b84e3e95f.png)

经过排查，editorRootDir:"/editor-md/" 会出这个问题，如果设置是 editorRootDir:"./static/editor-md/" 则不会报错

2、 总提示 ：Uncaught TypeError: t.editor.setMarkdown is not a function

![图片](https://user-images.githubusercontent.com/20489781/181013402-2471b940-2244-4f4e-96fe-8b4b46260f34.png)

**Comment by Aubrey-J** [comment]
抱歉，Github活跃度不高，才看到，给您使用带来不便，已更新了0.3.1版本解决了setMarkdown is not a function问题，您说的另一个问题，MIME 类型 "text/html" 不是 "text/css"，这个是因为build后的输出结构不同，所以访问资源路径不同，按需改动即可
